name: Deploy GOAT.CORP to PROD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          env: production
          step: start

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Netlify CLI
        run: pnpm add -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --build --message "production [${{ github.sha }}]"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NEXT_PUBLIC_RETAIL_CRM_API: ${{ secrets.NEXT_PUBLIC_RETAIL_CRM_API }}
          NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER: ${{secrets.NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER}}
          NEXT_PUBLIC_CDEK_SECRET: ${{secrets.NEXT_PUBLIC_CDEK_SECRET}}
          NEXT_PUBLIC_SITE_URL: ${{vars.NEXT_PUBLIC_SITE_URL}}
          NEXT_PUBLIC_ENVIRONMENT: ${{vars.NEXT_PUBLIC_ENVIRONMENT}}
          NEXT_PUBLIC_YANDEX_MAPS_SECRET: ${{secrets.NEXT_PUBLIC_YANDEX_MAPS_SECRET}}
          NEXT_PUBLIC_YOOKASSA_TEST_KEY: ${{secrets.NEXT_PUBLIC_YOOKASSA_TEST_KEY}}
          NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID: ${{vars.NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID}}
